# Generated by Django 6.0.3 on 2026-03-15 03:31

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('supported', 'Supported'), ('contradicted', 'Contradicted'), ('inconclusive', 'Inconclusive'), ('misleading', 'Misleading'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('citation_count', models.IntegerField(default=0)),
                ('abstract', models.TextField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_id', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('is_claim', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ClaimSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('excerpt', models.TextField()),
                ('supports', models.BooleanField()),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='footnote.claim')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footnote.paper')),
            ],
            options={
                'ordering': ['-similarity_score'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='papers',
            field=models.ManyToManyField(blank=True, through='footnote.ClaimSource', to='footnote.paper'),
        ),
        migrations.AddField(
            model_name='claim',
            name='sentence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='footnote.sentence'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='footnote.session'),
        ),
        migrations.AddField(
            model_name='claim',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='footnote.session'),
        ),
        migrations.CreateModel(
            name='PaperChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='footnote.paper')),
            ],
            options={
                'ordering': ['chunk_index'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_index', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='SavedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='footnote.paper')),
                ('saved_from_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='footnote.claim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'paper')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='sentence',
            unique_together={('session', 'order')},
        ),
    ]
