# Generated by Django 6.0.3 on 2026-03-15 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footnote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='sentence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='footnote.sentence'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='footnote.session'),
        ),
    ]
